imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, theme/src/*]

build:

    tests:
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"